# Generated by Django 6.1.1 on 2026-09-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={},
        ),
        migrations.RemoveField(
            model_name='finding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='calculated_at',
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.repository'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cloned', 'Cloned'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
